#!/usr/bin/env bash
#adding a custom header to the server
#!/usr/bin/env bash
# Installs nginx
# Configures it to listen on port 80
# Configures nginx so that its HTTP response contains a custom header
# Name of custom header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "21s/^listen .*/listen 80" /etc/nginx/sites-enabled/default
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html
sudo chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
file=/etc/nginx/sites-enabled/default
redirect="\     rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4/$1";
sudo sed -i " /server_name _;/a ${redirect} permanent;" $file
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
err="\        error_page\ 404 /custom_404.html;\n\        location\ = \ /custom_404.html\  {\n\t\troot\ /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "/server_name _;/a ${err}" $file
custom_header="\    add_header X-Served-By $HOSTNAME;"
sudo sed -i "/server_name _;/a ${custom_header}" $file
sudo service nginx restart
