#!/usr/bin/env bash
# install a new Nginx web server, and configure it so that its HTTP response contains a custom header
# name of the custom HTTP header must be X-Served-By
# value of the custom HTTP header must be the hostname of the server Nginx is running on
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/save_default
sed -i "/server_name _;/a add_header X-Served-By $HOSTNAME;\n" /etc/nginx/sites-available/default
service nginx restart
