#!/usr/bin/env bash
# Bash script that displays its own PID

trap "echo I hate the kill command; rm -f /var/run/myscript.pid; exit" SIGTERM
trap "echo Y U no love me?!" SIGINT
trap "rm -f /var/run/myscript.pid; exit" SIGQUIT

file=/var/run/myscript.pid
echo $$ >> $file

while :
do
    echo "To infinity and beyond"
    sleep 2
done