#!/usr/bin/env bash
# Bash script to fix the server Nginx
pkill -9 apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chown nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx bash -c 'service nginx start'
